# Server Port
server.port=8080

# Your cPanel Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/YOUR_CPANEL_DATABASE_NAME?useSSL=false&serverTimezone=UTC
spring.datasource.username=uumiscom_dbuumis
spring.datasource.password=Uumisadmin123!

# JPA / Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Keep your email settings here (Remember to use your NEW secret password!)
spring.mail.host=mail.uumis.com.my
spring.mail.port=465
spring.mail.username=dbadmin@uumis.com.my
spring.mail.password=#Dbadmin/222*
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true